version: "3"

services:
    spark_app:
        build:
            context: app
        image: gerardovitale/covid-spark-pipeline
        container_name: covid-spark-pipeline
        volumes:
            - ./app/data:/app/data
            - ./app/notebooks:/app/notebooks
        depends_on:
            - mongo_db

    flask_api:
        build:
            context: ./api
        image: gerardovitale/covid-flask-api
        container_name: covid-flask-api
        ports:
            - "5001:5001"
        depends_on:
            -   mongo_db

    mongo_db:
        image: mongo:3.6
        container_name: mongo_db
        restart: always
        ports: 
            - "27017:27017"
