version: "3"

services:
    app:
        build:
            context: .
        image: gerardovitale/covid-project
        container_name: covid-project
        ports:
            - "8888:8888"
        working_dir: /app
        volumes:
            - ./:/app
        depends_on:
            - mongo_db

    mongo_db:
        image: mongo:3.2
        container_name: mongo_db
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - /data/db:/data/db
