version: "3"

services:
    app:
        build:
            context: spark_app
        image: gerardovitale/covid-pipeline-app
        container_name: covid-pipeline-app
        working_dir: /spark_app
        volumes:
            - ./spark_app/:/spark_app
        depends_on:
            - mongo_db

    api:
        build:
            context: ./api
        image: gerardovitale/covid-api
        container_name: covid-api
        ports:
            - "5001:5001"

    mongo_db:
        image: mongo:3.6
        container_name: mongo_db
        restart: always
        ports: 
            - "27017:27017"
